#gui界面设置
inventory:
  #gui标题
  title: "§a分解界面"
  #点击分解物品设置
  itemStack:
    id: 145
    name: "§c点击分解"
    lore:
      - "§c点击分解"
      - "§c点击分解"
#消息,设置为none将不会发送
messages:
  success: "§a分解物品成功 §f<number> §a件"
  failed: "§c分解物品失败 §f<number> §c件"
  no-permission: "§c你没有权限执行这个命令！缺少权限: §4%permission%"
  not-a-player: "§c这个命令只能由玩家执行！"
  help-header: "§a=== HCFenJie 插件帮助 ==="
  help-command-help: "§b/fj help §7- 显示帮助信息"
  help-command-open: "§b/fj open §7- 打开分解界面"
  help-command-reload: "§b/fj reload §7- 重载配置文件"
  reload-success: "§a重载成功"
  open-success: "§a你成功打开了分解界面！"