name: HC-FenJie
version: '${project.version}'
main: com.hanchen.hcfenjie.Main
authors: [hanchen]
softdepend: [MythicMobs, NeigeItems]
commands:
  hcfj:
    aliases:
      - fj
permissions:
  hcfj.open:
    description: "打开分解界面"
  hcfj,reload:
    description: 允许重载插件配置
    default: op