name: HC-FenJie
version: '${project.version}'
main: com.hanchen.hcfenjie.Main
authors: [hanchen]
softdepend: [MythicMobs]
commands:
  hcfj:
    aliases:
      - fj
permissions:
  hcfj.open:
    description: "打开分解界面"
    default: op